import '/scss/style.scss';
import '/js/script.js';
import '/img/caravan-logo 1_1.png';
import '/img/Group 166.png';
import '/img/tea_1.jpg';
import '/img/tea_2.jpg';
import '/img/tea_3.jpg';
import '/img/caravan-logo 1_2.png';
import '/img/Group 134.png';
import '/img/Group 119.png';
import '/img/Group 120.png';
import '/img/Group 126.png';
import '/img/Group 130.png';
import '/img/Group 133.png';
import '/img/nathan-dumlao-c2Y16tC3yO8-unsplash 1.png';
import '/img/Ellipse 10.png';
